# Generated by Django 3.1.2 on 2021-07-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BriefIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('introduction', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
