# Generated by Django 3.1.2 on 2021-07-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeGraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistoryBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('answer_time', models.DateTimeField()),
                ('wrong_single_num', models.IntegerField()),
                ('single_score', models.IntegerField()),
                ('wrong_tf_num', models.IntegerField()),
                ('tf_score', models.IntegerField()),
                ('wrong_mul_num', models.IntegerField()),
                ('mul_score', models.IntegerField()),
                ('wrong_num', models.IntegerField()),
                ('score', models.IntegerField()),
                ('wrong_knowledge_points', models.TextField()),
            ],
        ),
    ]
